/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    certifications: Certification;
    categories: Category;
    products: Product;
    'blog-authors': BlogAuthor;
    'blog-categories': BlogCategory;
    'blog-tags': BlogTag;
    'blog-posts': BlogPost;
    events: Event;
    jobs: Job;
    news: News;
    awards: Award;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'blog-authors': BlogAuthorsSelect<false> | BlogAuthorsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'blog-tags': BlogTagsSelect<false> | BlogTagsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  name: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * External image URL (e.g. ImageKit)
   */
  imageUrl?: string | null;
  /**
   * Upload the certificate in PDF format
   */
  certificatePdf?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  heroImage?: (number | null) | Media;
  heroImageUrl?: string | null;
  homepageImage?: (number | null) | Media;
  homepageImageUrl?: string | null;
  /**
   * Number of products in this category
   */
  count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  productType?: ('standard' | 'branded' | 'vitamin-mineral' | 'probiotic') | null;
  category: number | Category;
  standardization?: string | null;
  latinName?: string | null;
  /**
   * Common name of the plant/ingredient
   */
  commonName?: string | null;
  plantPart?: string | null;
  /**
   * Minimum Order Quantity (e.g. 25 kg)
   */
  moq?: string | null;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  certifications?: (number | Certification)[] | null;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?:
    | {
        benefit?: string | null;
        id?: string | null;
      }[]
    | null;
  specifications?: {
    appearance?: string | null;
    solubility?: string | null;
    particleSize?: string | null;
    heavyMetals?: string | null;
    shelfLife?: string | null;
    storage?: string | null;
    activeCompounds?: string | null;
    testing?: string | null;
  };
  applications?:
    | {
        application?: string | null;
        image?: (number | null) | Media;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  research?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  /**
   * Only one product can be Product of the Month. Selecting this will automatically unset any other product.
   */
  productOfTheMonth?: boolean | null;
  /**
   * Custom tagline shown on homepage (e.g. "Trending Now")
   */
  productOfTheMonthTagline?: string | null;
  productionDetails?: {
    description?: string | null;
    image?: (number | null) | Media;
    imageUrl?: string | null;
  };
  packaging?: {
    description?: string | null;
    image?: (number | null) | Media;
    imageUrl?: string | null;
  };
  factory?: {
    description?: string | null;
    image?: (number | null) | Media;
    imageUrl?: string | null;
  };
  certificationsSection?: {
    description?: string | null;
    image?: (number | null) | Media;
    imageUrl?: string | null;
    images?:
      | {
          image?: (number | null) | Media;
          imageUrl?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  events?:
    | {
        description?: string | null;
        image?: (number | null) | Media;
        imageUrl?: string | null;
        images?:
          | {
              image?: (number | null) | Media;
              imageUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Product variants shown below specifications (e.g. Amla Extract - 20% Tannins - USP Grade)
   */
  variants?:
    | {
        /**
         * Full variant name (e.g. Amla Extract - 20% Tannins - USP Grade)
         */
        name: string;
        /**
         * Specification document (PDF) for download
         */
        specDocument?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (number | Product)[] | null;
  brandLogo?: (number | null) | Media;
  /**
   * External brand logo URL
   */
  brandLogoUrl?: string | null;
  clinicalResearch?: {
    title?: string | null;
    description?: string | null;
    studies?:
      | {
          title?: string | null;
          description?: string | null;
          link?: string | null;
          image?: (number | null) | Media;
          imageUrl?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  productIndications?: {
    title?: string | null;
    indications?:
      | {
          name?: string | null;
          icon?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  probioticDetails?: {
    sporesPerGram?: string | null;
    method?: string | null;
  };
  isParentProduct?: boolean | null;
  parentProduct?: (number | null) | Product;
  childProducts?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-authors".
 */
export interface BlogAuthor {
  id: number;
  name: string;
  role?: string | null;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  bio?: string | null;
  certificates?:
    | {
        certificate?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-tags".
 */
export interface BlogTag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  imageUrl?: string | null;
  publishedAt?: string | null;
  author: number | BlogAuthor;
  category: number | BlogCategory;
  tags?: (number | BlogTag)[] | null;
  readTime?: number | null;
  /**
   * Show this blog post in the homepage news ticker
   */
  showInNewsTicker?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  slug: string;
  startDate: string;
  endDate: string;
  location?: string | null;
  city?: string | null;
  country?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  boothNumber?: string | null;
  website?: string | null;
  upcoming?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  slug: string;
  department?: string | null;
  location?: string | null;
  /**
   * e.g. Full-time, Contract
   */
  type?: string | null;
  experience?: string | null;
  postedDate?: string | null;
  description?: string | null;
  responsibilities?:
    | {
        responsibility?: string | null;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        requirement?: string | null;
        id?: string | null;
      }[]
    | null;
  qualifications?:
    | {
        qualification?: string | null;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        benefit?: string | null;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  excerpt: string;
  date: string;
  /**
   * e.g. Product Launch, Events, Certifications, News, Innovation
   */
  category: string;
  image?: (number | null) | Media;
  /**
   * Fallback image URL if no media upload is provided
   */
  imageUrl?: string | null;
  /**
   * Optional link URL when clicking the news item
   */
  url?: string | null;
  /**
   * Show this news item in the ticker
   */
  active?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  title: string;
  year: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * External image URL (e.g. ImageKit)
   */
  imageUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'blog-authors';
        value: number | BlogAuthor;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog-tags';
        value: number | BlogTag;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  image?: T;
  imageUrl?: T;
  certificatePdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  longDescription?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  image?: T;
  imageUrl?: T;
  heroImage?: T;
  heroImageUrl?: T;
  homepageImage?: T;
  homepageImageUrl?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  productType?: T;
  category?: T;
  standardization?: T;
  latinName?: T;
  commonName?: T;
  plantPart?: T;
  moq?: T;
  image?: T;
  imageUrl?: T;
  certifications?: T;
  shortDescription?: T;
  description?: T;
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        appearance?: T;
        solubility?: T;
        particleSize?: T;
        heavyMetals?: T;
        shelfLife?: T;
        storage?: T;
        activeCompounds?: T;
        testing?: T;
      };
  applications?:
    | T
    | {
        application?: T;
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  research?: T;
  featured?: T;
  productOfTheMonth?: T;
  productOfTheMonthTagline?: T;
  productionDetails?:
    | T
    | {
        description?: T;
        image?: T;
        imageUrl?: T;
      };
  packaging?:
    | T
    | {
        description?: T;
        image?: T;
        imageUrl?: T;
      };
  factory?:
    | T
    | {
        description?: T;
        image?: T;
        imageUrl?: T;
      };
  certificationsSection?:
    | T
    | {
        description?: T;
        image?: T;
        imageUrl?: T;
        images?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              id?: T;
            };
      };
  events?:
    | T
    | {
        description?: T;
        image?: T;
        imageUrl?: T;
        images?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              id?: T;
            };
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        name?: T;
        specDocument?: T;
        id?: T;
      };
  relatedProducts?: T;
  brandLogo?: T;
  brandLogoUrl?: T;
  clinicalResearch?:
    | T
    | {
        title?: T;
        description?: T;
        studies?:
          | T
          | {
              title?: T;
              description?: T;
              link?: T;
              image?: T;
              imageUrl?: T;
              id?: T;
            };
      };
  productIndications?:
    | T
    | {
        title?: T;
        indications?:
          | T
          | {
              name?: T;
              icon?: T;
              description?: T;
              id?: T;
            };
      };
  probioticDetails?:
    | T
    | {
        sporesPerGram?: T;
        method?: T;
      };
  isParentProduct?: T;
  parentProduct?: T;
  childProducts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-authors_select".
 */
export interface BlogAuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  image?: T;
  imageUrl?: T;
  bio?: T;
  certificates?:
    | T
    | {
        certificate?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-tags_select".
 */
export interface BlogTagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  image?: T;
  imageUrl?: T;
  publishedAt?: T;
  author?: T;
  category?: T;
  tags?: T;
  readTime?: T;
  showInNewsTicker?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  city?: T;
  country?: T;
  description?: T;
  image?: T;
  imageUrl?: T;
  boothNumber?: T;
  website?: T;
  upcoming?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  department?: T;
  location?: T;
  type?: T;
  experience?: T;
  postedDate?: T;
  description?: T;
  responsibilities?:
    | T
    | {
        responsibility?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        requirement?: T;
        id?: T;
      };
  qualifications?:
    | T
    | {
        qualification?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  date?: T;
  category?: T;
  image?: T;
  imageUrl?: T;
  url?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  description?: T;
  image?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  general?: {
    siteTitle?: string | null;
    tagline?: string | null;
    copyrightText?: string | null;
  };
  contact?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  social?: {
    linkedin?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    /**
     * Leave empty to hide
     */
    twitter?: string | null;
    /**
     * Leave empty to hide
     */
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        siteTitle?: T;
        tagline?: T;
        copyrightText?: T;
      };
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
      };
  social?:
    | T
    | {
        linkedin?: T;
        facebook?: T;
        instagram?: T;
        twitter?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}